function Fixpunktkalibration = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  FIXPUNKTKALIBRATION = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  FIXPUNKTKALIBRATION = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  Fixpunktkalibration = importfile("C:\Users\Marvin\Desktop\Temperaturmessung\Fixpunktkalibration.csv", [17, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 01-Oct-2020 18:52:53

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [17, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 16);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["Scan", "Zeit", "RefC", "Alarm101", "P1_PT100_4LOHM", "Alarm102", "P2_PT100_2LOHM", "Alarm103", "P3_PT1000OHM", "Alarm104", "KTYOHM", "Alarm105", "NTCOHM", "Alarm106", "TEVDC", "Alarm107"];
opts.VariableTypes = ["double", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
opts = setvaropts(opts, 2, "WhitespaceRule", "preserve");
opts = setvaropts(opts, [3, 5, 7, 9, 11, 13, 15], "TrimNonNumeric", true);
opts = setvaropts(opts, [1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], "DecimalSeparator", ",");
opts = setvaropts(opts, [3, 5, 7, 9, 11, 13, 15], "ThousandsSeparator", ".");
opts = setvaropts(opts, 2, "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Fixpunktkalibration = readtable(filename, opts);

end