function x60l_h = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  X60L_H = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  X60L_H = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  x60l_h = importfile("C:\Users\Philipp\Desktop\Lena_Solarthermie\Praktika Solarthermie und thermische Messtechnik\Praktika Solarthermie und thermische Messtechnik\Durchflussmessung\DATA\60l-h_07.09.2020 16_15_40.csv", [17, 530]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 01-Oct-2020 11:36:07

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [17, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 16, "Encoding", "UTF16-LE");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["Scan", "Zeit", "Vortexinlproh", "Alarm103", "Ultraschall_stationrinlproh", "Alarm106", "T1C", "Alarm112", "T2C", "Alarm113", "MIDinlproh", "Alarm121", "Ultraschall_mobilinlproh", "Alarm122", "Ringkolbenzhler", "Alarm203"];
opts.VariableTypes = ["double", "datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Zeit", "InputFormat", "dd.MM.yyyy HH:mm:ss");
opts = setvaropts(opts, ["Scan", "Vortexinlproh", "Alarm103", "Ultraschall_stationrinlproh", "Alarm106", "T1C", "Alarm112", "T2C", "Alarm113", "MIDinlproh", "Alarm121", "Ultraschall_mobilinlproh", "Alarm122", "Ringkolbenzhler", "Alarm203"], "DecimalSeparator", ",");

% Import the data
x60l_h = readtable(filename, opts);

end