function Winddaten = importfile1(workbookFile, sheetName, dataLines)
%IMPORTFILE1 Import data from a spreadsheet
%  WINDDATEN = IMPORTFILE1(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the data as
%  a table.
%
%  WINDDATEN = IMPORTFILE1(FILE, SHEET) reads from the specified
%  worksheet.
%
%  WINDDATEN = IMPORTFILE1(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  Winddaten = importfile1("C:\Users\Marvin\Documents\Solarthermie_PT\Meterologische_Messgroessen\200901_Winddaten.xlsx", "Tabelle1", [2, 86401]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 04-Oct-2020 11:53:37

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 86401];
end

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":D" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Scan", "Zeit", "Windgeschwindigkeitinmpros", "WindrichtunginGrad"];
opts.SelectedVariableNames = ["Scan", "Zeit", "Windgeschwindigkeitinmpros", "WindrichtunginGrad"];
opts.VariableTypes = ["double", "datetime", "double", "double"];
opts = setvaropts(opts, 2, "InputFormat", "");

% Import the data
Winddaten = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":D" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    Winddaten = [Winddaten; tb]; %#ok<AGROW>
end

end