function RelativeLuftfeuchtTeilC04 = importfile1(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  RELATIVELUFTFEUCHTTEILC04 = IMPORTFILE1(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as a
%  table.
%
%  RELATIVELUFTFEUCHTTEILC04 = IMPORTFILE1(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  RelativeLuftfeuchtTeilC04 = importfile1("C:\Users\Marvin\Desktop\Uni\20 SS\Praktikum Solar\Luftfeuchte\Relative Luftfeucht_Teil_C04.09.2020 14_18_43.csv", [20, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03-Oct-2020 16:51:57

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [20, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 22);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["Scan", "Zeit", "Windgeschwindigkeitinmpros", "Alarm101", "WindrichtunginGrad", "Alarm102", "RelativeFeuchteinV", "Alarm103", "TemperatureC", "Alarm104", "TAGBS", "Alarm107", "ENNOSSSR81", "Alarm109", "CM3", "Alarm111", "CM11", "Alarm112", "CM11Schattenring", "Alarm113", "Niederschlag", "Alarm203"];
opts.VariableTypes = ["double", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
opts = setvaropts(opts, 2, "WhitespaceRule", "preserve");
opts = setvaropts(opts, [3, 5, 7, 9, 11, 13, 15, 17, 19], "TrimNonNumeric", true);
opts = setvaropts(opts, [1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22], "DecimalSeparator", ",");
opts = setvaropts(opts, [3, 5, 7, 9, 11, 13, 15, 17, 19], "ThousandsSeparator", ".");
opts = setvaropts(opts, 2, "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
RelativeLuftfeuchtTeilC04 = readtable(filename, opts);

end