function MeteoMessTeilBAnsprechzeiten = importfile1(workbookFile, sheetName, dataLines)
%IMPORTFILE1 Import data from a spreadsheet
%  METEOMESSTEILBANSPRECHZEITEN = IMPORTFILE1(FILE) reads data from the
%  first worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  METEOMESSTEILBANSPRECHZEITEN = IMPORTFILE1(FILE, SHEET) reads from
%  the specified worksheet.
%
%  METEOMESSTEILBANSPRECHZEITEN = IMPORTFILE1(FILE, SHEET, DATALINES)
%  reads from the specified worksheet for the specified row interval(s).
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  MeteoMessTeilBAnsprechzeiten = importfile1("C:\Users\Marvin\Documents\Solarthermie_PT\Meterologische_Messgroessen\190919_MeteoMess_Teil B_Ansprechzeiten.xlsx", "Teil B. Ansprechzeiten", [5, 366]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03-Oct-2020 21:51:25

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [5, 366];
end

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 7);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":G" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Scan", "Zeit", "VarName3", "TAGBS", "ENNOSSSR81", "CM3", "CM11"];
opts.SelectedVariableNames = ["Scan", "Zeit", "VarName3", "TAGBS", "ENNOSSSR81", "CM3", "CM11"];
opts.VariableTypes = ["double", "datetime", "double", "double", "double", "double", "double"];
opts = setvaropts(opts, 2, "InputFormat", "");

% Import the data
MeteoMessTeilBAnsprechzeiten = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":G" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    MeteoMessTeilBAnsprechzeiten = [MeteoMessTeilBAnsprechzeiten; tb]; %#ok<AGROW>
end

end