function SolarspeicherA07 = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  SOLARSPEICHERA07 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  SOLARSPEICHERA07 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  SolarspeicherA07 = importfile("C:\Users\Marvin\Documents\Solarthermie_PT\Solarthermische_Speicher\DATA\SolarspeicherA_07.09.2020 11_51_36.csv", [41, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 04-Oct-2020 14:58:15

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [41, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 64);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["Scan", "Zeit", "T_WT_sek_einC", "Alarm101", "T_WT_prim_ausC", "Alarm102", "T_WT_sek_ausC", "Alarm103", "T_WT_prim_einC", "Alarm104", "T_Steigrohr_ausC", "Alarm106", "T_WT_Speicher_einC", "Alarm107", "T_WT_Speicher_ausC", "Alarm108", "T_Heizer_einC", "Alarm110", "T_Heizer_ausC", "Alarm112", "MID_blau", "Alarm121", "MIDorange", "Alarm122", "T_Lanze_6cmC", "Alarm201", "T_Lanze_12cmC", "Alarm202", "T_Lanze_18cmC", "Alarm203", "T_Lanze_24cmC", "Alarm204", "T_Lanze_30cmC", "Alarm205", "T_Lanze_36cmC", "Alarm206", "T_Lanze_42cmC", "Alarm207", "T_Lanze_48cmC", "Alarm208", "T_Lanze_54cmC", "Alarm209", "T_Lanze_60cmC", "Alarm210", "T_Lanze_66cmC", "Alarm211", "T_Lanze_72cmC", "Alarm212", "T_Lanze_78cmC", "Alarm213", "T_Lanze_84cmC", "Alarm214", "T_Lanze_90cmC", "Alarm215", "T_Lanze_96cmC", "Alarm216", "T_Lanze_102cmC", "Alarm217", "T_Lanze_108cmC", "Alarm218", "T_Lanze_114cmC", "Alarm219", "T_Lanze_120cmC", "Alarm220"];
opts.VariableTypes = ["double", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
opts = setvaropts(opts, 2, "WhitespaceRule", "preserve");
opts = setvaropts(opts, [3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63], "TrimNonNumeric", true);
opts = setvaropts(opts, [1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64], "DecimalSeparator", ",");
opts = setvaropts(opts, [3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63], "ThousandsSeparator", ".");
opts = setvaropts(opts, 2, "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
SolarspeicherA07 = readtable(filename, opts);

end